kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: hello                  
spec:                                    
  containers:                      
    - name: c00                     
      image:sujata25/jenkins            
      command: ["/bin/bash", "-c", "while true; do echo Hello-world; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always
